version: 2
jobs:
  build-android:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/cmx
    steps:
      - checkout
      # - restore_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
      - run: chmod +x gradlew
      - run: cd cmx/cmx_android
      - run: pwd && ls -al
      - run: ./gradlew androidDependencies      
      # - run: ./gradlew dependencies
      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
      - run: ./gradlew build
      - store_artifacts:
          path: build/artifacts
  build-pc:
    docker:
      - image: circleci/jdk8:0.1.1
    working_directory: ~/cmx
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: cd cmx/cmx_pc
      - run: pwd && ls -al
      # - run: ./gradlew dependencies
      # - restore_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_pc/build.gradle" }}
      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_pc/build.gradle" }}      
      - run: ./gradlew build
      - store_artifacts:
          path: build/artifacts
  
workflows:
  version: 2
  build-android-and-pc:
    jobs:
      - build-pc
      - build-android
