version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run: chmod +x gradlew
      #- run: ./gradlew dependencies
      - run: ./gradlew build
      - store_artifacts:
        path: ./build
