version: 2
jobs:
  build-android:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/cmx_android
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
      - run: chmod +x gradlew
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
#         command: |          
#       - run: ./gradlew :app:assembleDebug
      - run: ./gradlew build
      
      - store_artifacts:
          path: build/outputs/aar
  build-pc:
    docker:
      - image: circleci/jdk8:0.1.1
    working_directory: ~/cmx_pc
    steps:
      - checkout
      - run: chmod +x gradlew
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_pc/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_pc/build.gradle" }}
      #- run: ./gradlew dependencies
      
      - run: ./gradlew build
      
      - store_artifacts:
          path: build/libs
  
workflows:
  version: 2
  build-android-and-pc:
    jobs:
      - build-android
      - build-pc
