version: 2
jobs:
  build-android:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/cmx
    steps:
      - checkout
      # - restore_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
      - run: chmod +x gradlew
      - run: ./gradlew androidDependencies      
      # - run: ./gradlew dependencies
      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_android/build.gradle" }}
      - run: ./gradlew -p cmx_android build
      # - run: ./gradlew build
      - store_artifacts:
          path: cmx_android/build/outputs/aar
  build-jre:
    docker:
      - image: circleci/jdk8:0.1.1
    working_directory: ~/cmx
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew -p cmx_jre build
      # - run: ./gradlew dependencies
      # - restore_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_jre/build.gradle" }}
      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cmx_jre/build.gradle" }}      
      # - run: ./gradlew build
      - store_artifacts:
          path: cmx_jre/build/libs
  
workflows:
  version: 2
  build-android-and-jre:
    jobs:
      - build-jre
      - build-android
