name: Publish cmx_android package to the GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      - run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: ./gradlew -p cmx_android assembleRelease publish
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
